# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_auto_20171017_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
