# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_auto_20171017_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='image',
            field=models.TextField(),
        ),
    ]
